#!/usr/bin/env bash
# This script configures localhost and facebook.com IP addresses in /etc/hosts

cp /etc/hosts /tmp/hosts
sed 's/^127\.0\.0\.1.*/127.0.0.2 localhost/' /tmp/hosts > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
